language: node_js
node_js:
- "6"
services: postgresql
before_install: sudo apt-get install -qq
install: npm install
before_script: psql -c 'CREATE DATABASE "llevame-server-test";' -U postgres
after_success: npm run coverage
