version: '2.1'
services:
  postgres:
    image: "postgres:9.4"
    ports: 
      - "5435:5432"
    volumes:
      - ./init_scripts.sql:/docker-entrypoint-initdb.d/1_init_scripts.sql
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_DB='llevame-server'
    healthcheck:
      test: exit 0
  web:
    build: .
    ports:
     - "5000:5000"
     - "3000:3000"
    volumes:
     - .:/usr/src/app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
     - DEV_DATABASE_URL=postgres://postgres:postgres@postgres:5432/llevame-server
    links:
      - postgres
    command: ["npm", "start"]