version: '2'
services:
  postgres:
    image: "postgres:9.4"
    environment:
     POSTGRES_PASSWORD: postgres
     POSTGRES_USER: postgres
  web:
    build: .
    ports:
     - "5000:5000"
     - "3000:3000"
    volumes:
     - ./init_scripts:/docker-entrypoint-initdb.d/
     - .:/usr/src/app
    depends_on:
      - postgres
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; npm start'